# Generated by Django 5.0.6 on 2024-07-26 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='商品名')),
                ('image', models.ImageField(null=True, upload_to='image', verbose_name='商品画像')),
                ('body', models.TextField(verbose_name='商品説明')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sakapansite.category')),
            ],
        ),
    ]
