# Generated by Django 5.0.6 on 2024-07-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakapansite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sakapansite.category', verbose_name='カテゴリー'),
        ),
    ]
